// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/grpc.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AttemptRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttemptRequest) Reset()         { *m = AttemptRequest{} }
func (m *AttemptRequest) String() string { return proto.CompactTextString(m) }
func (*AttemptRequest) ProtoMessage()    {}
func (*AttemptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1dd9633236863f3, []int{0}
}

func (m *AttemptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttemptRequest.Unmarshal(m, b)
}
func (m *AttemptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttemptRequest.Marshal(b, m, deterministic)
}
func (m *AttemptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttemptRequest.Merge(m, src)
}
func (m *AttemptRequest) XXX_Size() int {
	return xxx_messageInfo_AttemptRequest.Size(m)
}
func (m *AttemptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttemptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttemptRequest proto.InternalMessageInfo

func (m *AttemptRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AttemptRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AttemptRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type AttemptResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttemptResponse) Reset()         { *m = AttemptResponse{} }
func (m *AttemptResponse) String() string { return proto.CompactTextString(m) }
func (*AttemptResponse) ProtoMessage()    {}
func (*AttemptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1dd9633236863f3, []int{1}
}

func (m *AttemptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttemptResponse.Unmarshal(m, b)
}
func (m *AttemptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttemptResponse.Marshal(b, m, deterministic)
}
func (m *AttemptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttemptResponse.Merge(m, src)
}
func (m *AttemptResponse) XXX_Size() int {
	return xxx_messageInfo_AttemptResponse.Size(m)
}
func (m *AttemptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttemptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttemptResponse proto.InternalMessageInfo

func (m *AttemptResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AttemptResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type AddToBlacklistRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToBlacklistRequest) Reset()         { *m = AddToBlacklistRequest{} }
func (m *AddToBlacklistRequest) String() string { return proto.CompactTextString(m) }
func (*AddToBlacklistRequest) ProtoMessage()    {}
func (*AddToBlacklistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1dd9633236863f3, []int{2}
}

func (m *AddToBlacklistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToBlacklistRequest.Unmarshal(m, b)
}
func (m *AddToBlacklistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToBlacklistRequest.Marshal(b, m, deterministic)
}
func (m *AddToBlacklistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToBlacklistRequest.Merge(m, src)
}
func (m *AddToBlacklistRequest) XXX_Size() int {
	return xxx_messageInfo_AddToBlacklistRequest.Size(m)
}
func (m *AddToBlacklistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToBlacklistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToBlacklistRequest proto.InternalMessageInfo

func (m *AddToBlacklistRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type AddToBlacklistResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToBlacklistResponse) Reset()         { *m = AddToBlacklistResponse{} }
func (m *AddToBlacklistResponse) String() string { return proto.CompactTextString(m) }
func (*AddToBlacklistResponse) ProtoMessage()    {}
func (*AddToBlacklistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1dd9633236863f3, []int{3}
}

func (m *AddToBlacklistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToBlacklistResponse.Unmarshal(m, b)
}
func (m *AddToBlacklistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToBlacklistResponse.Marshal(b, m, deterministic)
}
func (m *AddToBlacklistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToBlacklistResponse.Merge(m, src)
}
func (m *AddToBlacklistResponse) XXX_Size() int {
	return xxx_messageInfo_AddToBlacklistResponse.Size(m)
}
func (m *AddToBlacklistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToBlacklistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddToBlacklistResponse proto.InternalMessageInfo

func (m *AddToBlacklistResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RemoveFromBlacklistRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromBlacklistRequest) Reset()         { *m = RemoveFromBlacklistRequest{} }
func (m *RemoveFromBlacklistRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFromBlacklistRequest) ProtoMessage()    {}
func (*RemoveFromBlacklistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1dd9633236863f3, []int{4}
}

func (m *RemoveFromBlacklistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromBlacklistRequest.Unmarshal(m, b)
}
func (m *RemoveFromBlacklistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromBlacklistRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFromBlacklistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromBlacklistRequest.Merge(m, src)
}
func (m *RemoveFromBlacklistRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFromBlacklistRequest.Size(m)
}
func (m *RemoveFromBlacklistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromBlacklistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromBlacklistRequest proto.InternalMessageInfo

func (m *RemoveFromBlacklistRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type RemoveFromBlacklistResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromBlacklistResponse) Reset()         { *m = RemoveFromBlacklistResponse{} }
func (m *RemoveFromBlacklistResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFromBlacklistResponse) ProtoMessage()    {}
func (*RemoveFromBlacklistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1dd9633236863f3, []int{5}
}

func (m *RemoveFromBlacklistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromBlacklistResponse.Unmarshal(m, b)
}
func (m *RemoveFromBlacklistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromBlacklistResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFromBlacklistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromBlacklistResponse.Merge(m, src)
}
func (m *RemoveFromBlacklistResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFromBlacklistResponse.Size(m)
}
func (m *RemoveFromBlacklistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromBlacklistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromBlacklistResponse proto.InternalMessageInfo

func (m *RemoveFromBlacklistResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type AddToWhitelistRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToWhitelistRequest) Reset()         { *m = AddToWhitelistRequest{} }
func (m *AddToWhitelistRequest) String() string { return proto.CompactTextString(m) }
func (*AddToWhitelistRequest) ProtoMessage()    {}
func (*AddToWhitelistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1dd9633236863f3, []int{6}
}

func (m *AddToWhitelistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToWhitelistRequest.Unmarshal(m, b)
}
func (m *AddToWhitelistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToWhitelistRequest.Marshal(b, m, deterministic)
}
func (m *AddToWhitelistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToWhitelistRequest.Merge(m, src)
}
func (m *AddToWhitelistRequest) XXX_Size() int {
	return xxx_messageInfo_AddToWhitelistRequest.Size(m)
}
func (m *AddToWhitelistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToWhitelistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToWhitelistRequest proto.InternalMessageInfo

func (m *AddToWhitelistRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type AddToWhitelistResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToWhitelistResponse) Reset()         { *m = AddToWhitelistResponse{} }
func (m *AddToWhitelistResponse) String() string { return proto.CompactTextString(m) }
func (*AddToWhitelistResponse) ProtoMessage()    {}
func (*AddToWhitelistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1dd9633236863f3, []int{7}
}

func (m *AddToWhitelistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToWhitelistResponse.Unmarshal(m, b)
}
func (m *AddToWhitelistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToWhitelistResponse.Marshal(b, m, deterministic)
}
func (m *AddToWhitelistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToWhitelistResponse.Merge(m, src)
}
func (m *AddToWhitelistResponse) XXX_Size() int {
	return xxx_messageInfo_AddToWhitelistResponse.Size(m)
}
func (m *AddToWhitelistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToWhitelistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddToWhitelistResponse proto.InternalMessageInfo

func (m *AddToWhitelistResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RemoveFromWhitelistRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromWhitelistRequest) Reset()         { *m = RemoveFromWhitelistRequest{} }
func (m *RemoveFromWhitelistRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFromWhitelistRequest) ProtoMessage()    {}
func (*RemoveFromWhitelistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1dd9633236863f3, []int{8}
}

func (m *RemoveFromWhitelistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromWhitelistRequest.Unmarshal(m, b)
}
func (m *RemoveFromWhitelistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromWhitelistRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFromWhitelistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromWhitelistRequest.Merge(m, src)
}
func (m *RemoveFromWhitelistRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFromWhitelistRequest.Size(m)
}
func (m *RemoveFromWhitelistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromWhitelistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromWhitelistRequest proto.InternalMessageInfo

func (m *RemoveFromWhitelistRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type RemoveFromWhitelistResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromWhitelistResponse) Reset()         { *m = RemoveFromWhitelistResponse{} }
func (m *RemoveFromWhitelistResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFromWhitelistResponse) ProtoMessage()    {}
func (*RemoveFromWhitelistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1dd9633236863f3, []int{9}
}

func (m *RemoveFromWhitelistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromWhitelistResponse.Unmarshal(m, b)
}
func (m *RemoveFromWhitelistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromWhitelistResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFromWhitelistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromWhitelistResponse.Merge(m, src)
}
func (m *RemoveFromWhitelistResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFromWhitelistResponse.Size(m)
}
func (m *RemoveFromWhitelistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromWhitelistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromWhitelistResponse proto.InternalMessageInfo

func (m *RemoveFromWhitelistResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*AttemptRequest)(nil), "api.AttemptRequest")
	proto.RegisterType((*AttemptResponse)(nil), "api.AttemptResponse")
	proto.RegisterType((*AddToBlacklistRequest)(nil), "api.AddToBlacklistRequest")
	proto.RegisterType((*AddToBlacklistResponse)(nil), "api.AddToBlacklistResponse")
	proto.RegisterType((*RemoveFromBlacklistRequest)(nil), "api.RemoveFromBlacklistRequest")
	proto.RegisterType((*RemoveFromBlacklistResponse)(nil), "api.RemoveFromBlacklistResponse")
	proto.RegisterType((*AddToWhitelistRequest)(nil), "api.AddToWhitelistRequest")
	proto.RegisterType((*AddToWhitelistResponse)(nil), "api.AddToWhitelistResponse")
	proto.RegisterType((*RemoveFromWhitelistRequest)(nil), "api.RemoveFromWhitelistRequest")
	proto.RegisterType((*RemoveFromWhitelistResponse)(nil), "api.RemoveFromWhitelistResponse")
}

func init() { proto.RegisterFile("api/grpc.proto", fileDescriptor_c1dd9633236863f3) }

var fileDescriptor_c1dd9633236863f3 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x4f, 0xb3, 0x40,
	0x10, 0x87, 0x03, 0xa4, 0x7d, 0xdb, 0x39, 0xf0, 0x26, 0xdb, 0xda, 0x90, 0xed, 0x41, 0xc2, 0x45,
	0x0f, 0x06, 0x8d, 0x7f, 0x0e, 0x1e, 0xe1, 0x60, 0xe2, 0x15, 0x4d, 0x34, 0xde, 0x56, 0xd8, 0xd4,
	0x0d, 0xd0, 0x5d, 0xd9, 0x6d, 0xfd, 0x10, 0x7e, 0x69, 0x53, 0x40, 0x04, 0x0a, 0x52, 0x8f, 0xc3,
	0xfe, 0xf6, 0x99, 0x27, 0x33, 0x2c, 0x98, 0x44, 0xb0, 0xf3, 0x55, 0x26, 0x42, 0x57, 0x64, 0x5c,
	0x71, 0x64, 0x10, 0xc1, 0x9c, 0x00, 0x4c, 0x4f, 0x29, 0x9a, 0x0a, 0x15, 0xd0, 0xf7, 0x0d, 0x95,
	0x0a, 0xcd, 0x61, 0x94, 0xf0, 0x15, 0x5b, 0x5b, 0x9a, 0xad, 0x9d, 0x4e, 0x83, 0xa2, 0x40, 0x18,
	0x26, 0x82, 0x48, 0xf9, 0xc1, 0xb3, 0xc8, 0xd2, 0xf3, 0x83, 0xaa, 0x46, 0x26, 0xe8, 0x4c, 0x58,
	0x46, 0xfe, 0x55, 0x67, 0xc2, 0xb9, 0x85, 0xff, 0x15, 0x53, 0x0a, 0xbe, 0x96, 0x14, 0x2d, 0x60,
	0x2c, 0x15, 0x51, 0x1b, 0x59, 0x52, 0xcb, 0x6a, 0x77, 0x95, 0xc7, 0x39, 0x70, 0x12, 0xe8, 0x3c,
	0x76, 0x4e, 0xe0, 0xc8, 0x8b, 0xa2, 0x47, 0xee, 0x27, 0x24, 0x8c, 0x13, 0x26, 0x2b, 0xab, 0xa2,
	0x87, 0x56, 0xf5, 0xb8, 0x80, 0x45, 0x3b, 0xf8, 0x7b, 0x2b, 0xe7, 0x0c, 0x70, 0x40, 0x53, 0xbe,
	0xa5, 0x77, 0x19, 0x4f, 0x07, 0xf9, 0x37, 0xb0, 0xec, 0x4c, 0x0f, 0x34, 0xf9, 0xf6, 0x7f, 0x7a,
	0x63, 0x8a, 0x1e, 0xe2, 0x5f, 0x0b, 0xfe, 0xc5, 0x7f, 0x90, 0xdf, 0xf0, 0x3f, 0xb8, 0xc9, 0xe5,
	0xa7, 0x01, 0x53, 0xcf, 0x7f, 0xa0, 0xd9, 0x96, 0x85, 0x14, 0x5d, 0xc3, 0xbf, 0x72, 0x91, 0x68,
	0xe6, 0x12, 0xc1, 0xdc, 0xe6, 0xaf, 0x82, 0xe7, 0xcd, 0x8f, 0x25, 0xfb, 0x1e, 0xcc, 0xe6, 0x6a,
	0x10, 0x2e, 0x72, 0x5d, 0x8b, 0xc5, 0xcb, 0xce, 0xb3, 0x12, 0xf5, 0x0c, 0xb3, 0x8e, 0x2d, 0xa0,
	0xe3, 0xfc, 0x4e, 0xff, 0x36, 0xb1, 0xdd, 0x1f, 0x68, 0x49, 0x56, 0xa3, 0xa9, 0x4b, 0xb6, 0xa7,
	0x5b, 0x97, 0xdc, 0x9f, 0x65, 0x43, 0xf2, 0x87, 0xd7, 0x96, 0xdc, 0x83, 0xda, 0xfd, 0x81, 0x82,
	0xec, 0x8f, 0x5e, 0x76, 0x6f, 0xf4, 0x75, 0x9c, 0xbf, 0xd7, 0xab, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x9c, 0xf7, 0xb7, 0x09, 0xc1, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ABServiceClient is the client API for ABService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ABServiceClient interface {
	Attempt(ctx context.Context, in *AttemptRequest, opts ...grpc.CallOption) (*AttemptResponse, error)
	AddToBlacklist(ctx context.Context, in *AddToBlacklistRequest, opts ...grpc.CallOption) (*AddToBlacklistResponse, error)
	RemoveFromBlacklist(ctx context.Context, in *RemoveFromBlacklistRequest, opts ...grpc.CallOption) (*RemoveFromBlacklistResponse, error)
	AddToWhitelist(ctx context.Context, in *AddToWhitelistRequest, opts ...grpc.CallOption) (*AddToWhitelistResponse, error)
	RemoveFromWhitelist(ctx context.Context, in *RemoveFromWhitelistRequest, opts ...grpc.CallOption) (*RemoveFromWhitelistResponse, error)
}

type aBServiceClient struct {
	cc *grpc.ClientConn
}

func NewABServiceClient(cc *grpc.ClientConn) ABServiceClient {
	return &aBServiceClient{cc}
}

func (c *aBServiceClient) Attempt(ctx context.Context, in *AttemptRequest, opts ...grpc.CallOption) (*AttemptResponse, error) {
	out := new(AttemptResponse)
	err := c.cc.Invoke(ctx, "/api.ABService/Attempt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBServiceClient) AddToBlacklist(ctx context.Context, in *AddToBlacklistRequest, opts ...grpc.CallOption) (*AddToBlacklistResponse, error) {
	out := new(AddToBlacklistResponse)
	err := c.cc.Invoke(ctx, "/api.ABService/AddToBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBServiceClient) RemoveFromBlacklist(ctx context.Context, in *RemoveFromBlacklistRequest, opts ...grpc.CallOption) (*RemoveFromBlacklistResponse, error) {
	out := new(RemoveFromBlacklistResponse)
	err := c.cc.Invoke(ctx, "/api.ABService/RemoveFromBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBServiceClient) AddToWhitelist(ctx context.Context, in *AddToWhitelistRequest, opts ...grpc.CallOption) (*AddToWhitelistResponse, error) {
	out := new(AddToWhitelistResponse)
	err := c.cc.Invoke(ctx, "/api.ABService/AddToWhitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBServiceClient) RemoveFromWhitelist(ctx context.Context, in *RemoveFromWhitelistRequest, opts ...grpc.CallOption) (*RemoveFromWhitelistResponse, error) {
	out := new(RemoveFromWhitelistResponse)
	err := c.cc.Invoke(ctx, "/api.ABService/RemoveFromWhitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ABServiceServer is the server API for ABService service.
type ABServiceServer interface {
	Attempt(context.Context, *AttemptRequest) (*AttemptResponse, error)
	AddToBlacklist(context.Context, *AddToBlacklistRequest) (*AddToBlacklistResponse, error)
	RemoveFromBlacklist(context.Context, *RemoveFromBlacklistRequest) (*RemoveFromBlacklistResponse, error)
	AddToWhitelist(context.Context, *AddToWhitelistRequest) (*AddToWhitelistResponse, error)
	RemoveFromWhitelist(context.Context, *RemoveFromWhitelistRequest) (*RemoveFromWhitelistResponse, error)
}

// UnimplementedABServiceServer can be embedded to have forward compatible implementations.
type UnimplementedABServiceServer struct {
}

func (*UnimplementedABServiceServer) Attempt(ctx context.Context, req *AttemptRequest) (*AttemptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attempt not implemented")
}
func (*UnimplementedABServiceServer) AddToBlacklist(ctx context.Context, req *AddToBlacklistRequest) (*AddToBlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToBlacklist not implemented")
}
func (*UnimplementedABServiceServer) RemoveFromBlacklist(ctx context.Context, req *RemoveFromBlacklistRequest) (*RemoveFromBlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromBlacklist not implemented")
}
func (*UnimplementedABServiceServer) AddToWhitelist(ctx context.Context, req *AddToWhitelistRequest) (*AddToWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToWhitelist not implemented")
}
func (*UnimplementedABServiceServer) RemoveFromWhitelist(ctx context.Context, req *RemoveFromWhitelistRequest) (*RemoveFromWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromWhitelist not implemented")
}

func RegisterABServiceServer(s *grpc.Server, srv ABServiceServer) {
	s.RegisterService(&_ABService_serviceDesc, srv)
}

func _ABService_Attempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABServiceServer).Attempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ABService/Attempt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABServiceServer).Attempt(ctx, req.(*AttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABService_AddToBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABServiceServer).AddToBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ABService/AddToBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABServiceServer).AddToBlacklist(ctx, req.(*AddToBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABService_RemoveFromBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABServiceServer).RemoveFromBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ABService/RemoveFromBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABServiceServer).RemoveFromBlacklist(ctx, req.(*RemoveFromBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABService_AddToWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABServiceServer).AddToWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ABService/AddToWhitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABServiceServer).AddToWhitelist(ctx, req.(*AddToWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABService_RemoveFromWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABServiceServer).RemoveFromWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ABService/RemoveFromWhitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABServiceServer).RemoveFromWhitelist(ctx, req.(*RemoveFromWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ABService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ABService",
	HandlerType: (*ABServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Attempt",
			Handler:    _ABService_Attempt_Handler,
		},
		{
			MethodName: "AddToBlacklist",
			Handler:    _ABService_AddToBlacklist_Handler,
		},
		{
			MethodName: "RemoveFromBlacklist",
			Handler:    _ABService_RemoveFromBlacklist_Handler,
		},
		{
			MethodName: "AddToWhitelist",
			Handler:    _ABService_AddToWhitelist_Handler,
		},
		{
			MethodName: "RemoveFromWhitelist",
			Handler:    _ABService_RemoveFromWhitelist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc.proto",
}
