// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/grpc.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AttemptRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttemptRequest) Reset()         { *m = AttemptRequest{} }
func (m *AttemptRequest) String() string { return proto.CompactTextString(m) }
func (*AttemptRequest) ProtoMessage()    {}
func (*AttemptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a889fb3fc4b84f77, []int{0}
}
func (m *AttemptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttemptRequest.Unmarshal(m, b)
}
func (m *AttemptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttemptRequest.Marshal(b, m, deterministic)
}
func (dst *AttemptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttemptRequest.Merge(dst, src)
}
func (m *AttemptRequest) XXX_Size() int {
	return xxx_messageInfo_AttemptRequest.Size(m)
}
func (m *AttemptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttemptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttemptRequest proto.InternalMessageInfo

func (m *AttemptRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AttemptRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AttemptRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type AttemptResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttemptResponse) Reset()         { *m = AttemptResponse{} }
func (m *AttemptResponse) String() string { return proto.CompactTextString(m) }
func (*AttemptResponse) ProtoMessage()    {}
func (*AttemptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a889fb3fc4b84f77, []int{1}
}
func (m *AttemptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttemptResponse.Unmarshal(m, b)
}
func (m *AttemptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttemptResponse.Marshal(b, m, deterministic)
}
func (dst *AttemptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttemptResponse.Merge(dst, src)
}
func (m *AttemptResponse) XXX_Size() int {
	return xxx_messageInfo_AttemptResponse.Size(m)
}
func (m *AttemptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttemptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttemptResponse proto.InternalMessageInfo

func (m *AttemptResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AttemptResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type AddToBlacklistRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToBlacklistRequest) Reset()         { *m = AddToBlacklistRequest{} }
func (m *AddToBlacklistRequest) String() string { return proto.CompactTextString(m) }
func (*AddToBlacklistRequest) ProtoMessage()    {}
func (*AddToBlacklistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a889fb3fc4b84f77, []int{2}
}
func (m *AddToBlacklistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToBlacklistRequest.Unmarshal(m, b)
}
func (m *AddToBlacklistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToBlacklistRequest.Marshal(b, m, deterministic)
}
func (dst *AddToBlacklistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToBlacklistRequest.Merge(dst, src)
}
func (m *AddToBlacklistRequest) XXX_Size() int {
	return xxx_messageInfo_AddToBlacklistRequest.Size(m)
}
func (m *AddToBlacklistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToBlacklistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToBlacklistRequest proto.InternalMessageInfo

func (m *AddToBlacklistRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type AddToBlacklistResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToBlacklistResponse) Reset()         { *m = AddToBlacklistResponse{} }
func (m *AddToBlacklistResponse) String() string { return proto.CompactTextString(m) }
func (*AddToBlacklistResponse) ProtoMessage()    {}
func (*AddToBlacklistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a889fb3fc4b84f77, []int{3}
}
func (m *AddToBlacklistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToBlacklistResponse.Unmarshal(m, b)
}
func (m *AddToBlacklistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToBlacklistResponse.Marshal(b, m, deterministic)
}
func (dst *AddToBlacklistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToBlacklistResponse.Merge(dst, src)
}
func (m *AddToBlacklistResponse) XXX_Size() int {
	return xxx_messageInfo_AddToBlacklistResponse.Size(m)
}
func (m *AddToBlacklistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToBlacklistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddToBlacklistResponse proto.InternalMessageInfo

func (m *AddToBlacklistResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RemoveFromBlacklistRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromBlacklistRequest) Reset()         { *m = RemoveFromBlacklistRequest{} }
func (m *RemoveFromBlacklistRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFromBlacklistRequest) ProtoMessage()    {}
func (*RemoveFromBlacklistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a889fb3fc4b84f77, []int{4}
}
func (m *RemoveFromBlacklistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromBlacklistRequest.Unmarshal(m, b)
}
func (m *RemoveFromBlacklistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromBlacklistRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveFromBlacklistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromBlacklistRequest.Merge(dst, src)
}
func (m *RemoveFromBlacklistRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFromBlacklistRequest.Size(m)
}
func (m *RemoveFromBlacklistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromBlacklistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromBlacklistRequest proto.InternalMessageInfo

func (m *RemoveFromBlacklistRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type RemoveFromBlacklistResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromBlacklistResponse) Reset()         { *m = RemoveFromBlacklistResponse{} }
func (m *RemoveFromBlacklistResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFromBlacklistResponse) ProtoMessage()    {}
func (*RemoveFromBlacklistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a889fb3fc4b84f77, []int{5}
}
func (m *RemoveFromBlacklistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromBlacklistResponse.Unmarshal(m, b)
}
func (m *RemoveFromBlacklistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromBlacklistResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveFromBlacklistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromBlacklistResponse.Merge(dst, src)
}
func (m *RemoveFromBlacklistResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFromBlacklistResponse.Size(m)
}
func (m *RemoveFromBlacklistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromBlacklistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromBlacklistResponse proto.InternalMessageInfo

func (m *RemoveFromBlacklistResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type AddToWhitelistRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToWhitelistRequest) Reset()         { *m = AddToWhitelistRequest{} }
func (m *AddToWhitelistRequest) String() string { return proto.CompactTextString(m) }
func (*AddToWhitelistRequest) ProtoMessage()    {}
func (*AddToWhitelistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a889fb3fc4b84f77, []int{6}
}
func (m *AddToWhitelistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToWhitelistRequest.Unmarshal(m, b)
}
func (m *AddToWhitelistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToWhitelistRequest.Marshal(b, m, deterministic)
}
func (dst *AddToWhitelistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToWhitelistRequest.Merge(dst, src)
}
func (m *AddToWhitelistRequest) XXX_Size() int {
	return xxx_messageInfo_AddToWhitelistRequest.Size(m)
}
func (m *AddToWhitelistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToWhitelistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToWhitelistRequest proto.InternalMessageInfo

func (m *AddToWhitelistRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type AddToWhitelistResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToWhitelistResponse) Reset()         { *m = AddToWhitelistResponse{} }
func (m *AddToWhitelistResponse) String() string { return proto.CompactTextString(m) }
func (*AddToWhitelistResponse) ProtoMessage()    {}
func (*AddToWhitelistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a889fb3fc4b84f77, []int{7}
}
func (m *AddToWhitelistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToWhitelistResponse.Unmarshal(m, b)
}
func (m *AddToWhitelistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToWhitelistResponse.Marshal(b, m, deterministic)
}
func (dst *AddToWhitelistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToWhitelistResponse.Merge(dst, src)
}
func (m *AddToWhitelistResponse) XXX_Size() int {
	return xxx_messageInfo_AddToWhitelistResponse.Size(m)
}
func (m *AddToWhitelistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToWhitelistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddToWhitelistResponse proto.InternalMessageInfo

func (m *AddToWhitelistResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RemoveFromWhitelistRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromWhitelistRequest) Reset()         { *m = RemoveFromWhitelistRequest{} }
func (m *RemoveFromWhitelistRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFromWhitelistRequest) ProtoMessage()    {}
func (*RemoveFromWhitelistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a889fb3fc4b84f77, []int{8}
}
func (m *RemoveFromWhitelistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromWhitelistRequest.Unmarshal(m, b)
}
func (m *RemoveFromWhitelistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromWhitelistRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveFromWhitelistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromWhitelistRequest.Merge(dst, src)
}
func (m *RemoveFromWhitelistRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFromWhitelistRequest.Size(m)
}
func (m *RemoveFromWhitelistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromWhitelistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromWhitelistRequest proto.InternalMessageInfo

func (m *RemoveFromWhitelistRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type RemoveFromWhitelistResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFromWhitelistResponse) Reset()         { *m = RemoveFromWhitelistResponse{} }
func (m *RemoveFromWhitelistResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFromWhitelistResponse) ProtoMessage()    {}
func (*RemoveFromWhitelistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a889fb3fc4b84f77, []int{9}
}
func (m *RemoveFromWhitelistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFromWhitelistResponse.Unmarshal(m, b)
}
func (m *RemoveFromWhitelistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFromWhitelistResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveFromWhitelistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFromWhitelistResponse.Merge(dst, src)
}
func (m *RemoveFromWhitelistResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFromWhitelistResponse.Size(m)
}
func (m *RemoveFromWhitelistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFromWhitelistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFromWhitelistResponse proto.InternalMessageInfo

func (m *RemoveFromWhitelistResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*AttemptRequest)(nil), "api.AttemptRequest")
	proto.RegisterType((*AttemptResponse)(nil), "api.AttemptResponse")
	proto.RegisterType((*AddToBlacklistRequest)(nil), "api.AddToBlacklistRequest")
	proto.RegisterType((*AddToBlacklistResponse)(nil), "api.AddToBlacklistResponse")
	proto.RegisterType((*RemoveFromBlacklistRequest)(nil), "api.RemoveFromBlacklistRequest")
	proto.RegisterType((*RemoveFromBlacklistResponse)(nil), "api.RemoveFromBlacklistResponse")
	proto.RegisterType((*AddToWhitelistRequest)(nil), "api.AddToWhitelistRequest")
	proto.RegisterType((*AddToWhitelistResponse)(nil), "api.AddToWhitelistResponse")
	proto.RegisterType((*RemoveFromWhitelistRequest)(nil), "api.RemoveFromWhitelistRequest")
	proto.RegisterType((*RemoveFromWhitelistResponse)(nil), "api.RemoveFromWhitelistResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	Attempt(ctx context.Context, in *AttemptRequest, opts ...grpc.CallOption) (*AttemptResponse, error)
	AddToBlacklist(ctx context.Context, in *AddToBlacklistRequest, opts ...grpc.CallOption) (*AddToBlacklistResponse, error)
	RemoveFromBlacklist(ctx context.Context, in *RemoveFromBlacklistRequest, opts ...grpc.CallOption) (*RemoveFromBlacklistResponse, error)
	AddToWhitelist(ctx context.Context, in *AddToWhitelistRequest, opts ...grpc.CallOption) (*AddToWhitelistResponse, error)
	RemoveFromWhite(ctx context.Context, in *RemoveFromWhitelistRequest, opts ...grpc.CallOption) (*RemoveFromWhitelistResponse, error)
}

type eventServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventServiceClient(cc *grpc.ClientConn) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) Attempt(ctx context.Context, in *AttemptRequest, opts ...grpc.CallOption) (*AttemptResponse, error) {
	out := new(AttemptResponse)
	err := c.cc.Invoke(ctx, "/api.EventService/Attempt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) AddToBlacklist(ctx context.Context, in *AddToBlacklistRequest, opts ...grpc.CallOption) (*AddToBlacklistResponse, error) {
	out := new(AddToBlacklistResponse)
	err := c.cc.Invoke(ctx, "/api.EventService/AddToBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) RemoveFromBlacklist(ctx context.Context, in *RemoveFromBlacklistRequest, opts ...grpc.CallOption) (*RemoveFromBlacklistResponse, error) {
	out := new(RemoveFromBlacklistResponse)
	err := c.cc.Invoke(ctx, "/api.EventService/RemoveFromBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) AddToWhitelist(ctx context.Context, in *AddToWhitelistRequest, opts ...grpc.CallOption) (*AddToWhitelistResponse, error) {
	out := new(AddToWhitelistResponse)
	err := c.cc.Invoke(ctx, "/api.EventService/AddToWhitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) RemoveFromWhite(ctx context.Context, in *RemoveFromWhitelistRequest, opts ...grpc.CallOption) (*RemoveFromWhitelistResponse, error) {
	out := new(RemoveFromWhitelistResponse)
	err := c.cc.Invoke(ctx, "/api.EventService/RemoveFromWhite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	Attempt(context.Context, *AttemptRequest) (*AttemptResponse, error)
	AddToBlacklist(context.Context, *AddToBlacklistRequest) (*AddToBlacklistResponse, error)
	RemoveFromBlacklist(context.Context, *RemoveFromBlacklistRequest) (*RemoveFromBlacklistResponse, error)
	AddToWhitelist(context.Context, *AddToWhitelistRequest) (*AddToWhitelistResponse, error)
	RemoveFromWhite(context.Context, *RemoveFromWhitelistRequest) (*RemoveFromWhitelistResponse, error)
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_Attempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Attempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EventService/Attempt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Attempt(ctx, req.(*AttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_AddToBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).AddToBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EventService/AddToBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).AddToBlacklist(ctx, req.(*AddToBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_RemoveFromBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).RemoveFromBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EventService/RemoveFromBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).RemoveFromBlacklist(ctx, req.(*RemoveFromBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_AddToWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).AddToWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EventService/AddToWhitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).AddToWhitelist(ctx, req.(*AddToWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_RemoveFromWhite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).RemoveFromWhite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EventService/RemoveFromWhite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).RemoveFromWhite(ctx, req.(*RemoveFromWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Attempt",
			Handler:    _EventService_Attempt_Handler,
		},
		{
			MethodName: "AddToBlacklist",
			Handler:    _EventService_AddToBlacklist_Handler,
		},
		{
			MethodName: "RemoveFromBlacklist",
			Handler:    _EventService_RemoveFromBlacklist_Handler,
		},
		{
			MethodName: "AddToWhitelist",
			Handler:    _EventService_AddToWhitelist_Handler,
		},
		{
			MethodName: "RemoveFromWhite",
			Handler:    _EventService_RemoveFromWhite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc.proto",
}

func init() { proto.RegisterFile("api/grpc.proto", fileDescriptor_grpc_a889fb3fc4b84f77) }

var fileDescriptor_grpc_a889fb3fc4b84f77 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4b, 0x4b, 0xfb, 0x40,
	0x14, 0xc5, 0x69, 0x4a, 0xfb, 0xef, 0xff, 0x22, 0x29, 0x4c, 0x6b, 0x09, 0xd3, 0x85, 0x21, 0x1b,
	0x5d, 0x48, 0x14, 0x1f, 0x0b, 0x97, 0x2d, 0x28, 0xb8, 0x8d, 0x05, 0xc5, 0xdd, 0x98, 0x0c, 0x75,
	0xc8, 0x63, 0xc6, 0xcc, 0x34, 0x7e, 0x07, 0x3f, 0xb5, 0x34, 0x89, 0x21, 0x4f, 0x53, 0x97, 0x37,
	0x73, 0xe6, 0x9c, 0x1f, 0xf7, 0x64, 0x40, 0x27, 0x82, 0x5d, 0x6c, 0x63, 0xe1, 0xda, 0x22, 0xe6,
	0x8a, 0xa3, 0x21, 0x11, 0xcc, 0x72, 0x40, 0x5f, 0x29, 0x45, 0x43, 0xa1, 0x1c, 0xfa, 0xb1, 0xa3,
	0x52, 0xa1, 0x39, 0x8c, 0x02, 0xbe, 0x65, 0x91, 0x31, 0x30, 0x07, 0x67, 0xff, 0x9d, 0x6c, 0x40,
	0x18, 0x26, 0x82, 0x48, 0xf9, 0xc9, 0x63, 0xcf, 0xd0, 0xd2, 0x83, 0x62, 0x46, 0x3a, 0x68, 0x4c,
	0x18, 0xc3, 0xf4, 0xab, 0xc6, 0x84, 0x75, 0x07, 0xd3, 0xc2, 0x53, 0x0a, 0x1e, 0x49, 0x8a, 0x16,
	0x30, 0x96, 0x8a, 0xa8, 0x9d, 0xcc, 0x5d, 0xf3, 0x69, 0x7f, 0x95, 0xfb, 0xa9, 0xe1, 0xc4, 0xd1,
	0xb8, 0x6f, 0x9d, 0xc2, 0xf1, 0xca, 0xf3, 0x36, 0x7c, 0x1d, 0x10, 0xd7, 0x0f, 0x98, 0x2c, 0xa8,
	0xb2, 0x8c, 0x41, 0x91, 0x71, 0x09, 0x8b, 0xba, 0xf0, 0xf7, 0x28, 0xeb, 0x1c, 0xb0, 0x43, 0x43,
	0x9e, 0xd0, 0x87, 0x98, 0x87, 0xbd, 0xfe, 0xb7, 0xb0, 0x6c, 0x55, 0xf7, 0x84, 0xfc, 0xf0, 0x3f,
	0xbf, 0x33, 0x45, 0x0f, 0xe1, 0x2f, 0x09, 0xff, 0xc2, 0xdf, 0xeb, 0x5f, 0xe1, 0x3f, 0x38, 0xe4,
	0xea, 0x6b, 0x08, 0x47, 0xf7, 0x09, 0x8d, 0xd4, 0x13, 0x8d, 0x13, 0xe6, 0x52, 0x74, 0x03, 0xff,
	0xf2, 0x2e, 0xd1, 0xcc, 0x26, 0x82, 0xd9, 0xd5, 0xbf, 0x05, 0xcf, 0xab, 0x1f, 0x73, 0xfb, 0x47,
	0xd0, 0xab, 0xed, 0x20, 0x9c, 0xe9, 0xda, 0xba, 0xc5, 0xcb, 0xd6, 0xb3, 0xdc, 0xea, 0x05, 0x66,
	0x2d, 0x45, 0xa0, 0x93, 0xf4, 0x4e, 0x77, 0xa1, 0xd8, 0xec, 0x16, 0xd4, 0x20, 0x8b, 0xed, 0x94,
	0x21, 0xeb, 0x0b, 0x2e, 0x43, 0x36, 0xd7, 0xb9, 0x81, 0x69, 0x6d, 0xdb, 0x0d, 0xc0, 0x86, 0xa1,
	0xd9, 0x2d, 0xc8, 0x5c, 0xd7, 0xa3, 0xd7, 0xfd, 0x13, 0x7d, 0x1b, 0xa7, 0xcf, 0xf5, 0xfa, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0xed, 0x53, 0x4b, 0x31, 0xc0, 0x03, 0x00, 0x00,
}
